### ISSUE TITLE
複数プラットフォーム用の同時リリース

### ISSUE THREAD

**Issue by nnnnusui** [nnnnusui/tryActions#11]
```
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [windows-latest, ubuntu-latest, macos-latest]
```
・・・？
